// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientRestSDKLibrary
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for ClientRestSDKLibraryClient.
    /// </summary>
    public static partial class ClientRestSDKLibraryClientExtensions
    {
            /// <summary>
            /// This endpoint allows a user to submit a move and receive a bot's
            /// responding move
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// </param>
            public static ExecuteMoveResponse ExecuteMove(this IClientRestSDKLibraryClient operations, MessagePayload body = default(MessagePayload))
            {
                return Task.Factory.StartNew(s => ((IClientRestSDKLibraryClient)s).ExecuteMoveAsync(body), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// This endpoint allows a user to submit a move and receive a bot's
            /// responding move
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ExecuteMoveResponse> ExecuteMoveAsync(this IClientRestSDKLibraryClient operations, MessagePayload body = default(MessagePayload), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ExecuteMoveWithHttpMessagesAsync(body, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
