// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ClientRestSDKLibrary.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Defines the response for executemove
    /// </summary>
    public partial class ExecuteMoveResponse
    {
        /// <summary>
        /// Initializes a new instance of the ExecuteMoveResponse class.
        /// </summary>
        public ExecuteMoveResponse() { }

        /// <summary>
        /// Initializes a new instance of the ExecuteMoveResponse class.
        /// </summary>
        public ExecuteMoveResponse(int? move = default(int?), string azurePlayerSymbol = default(string), string humanPlayerSymbol = default(string), string winner = default(string), IList<int?> winPositions = default(IList<int?>), IList<string> gameBoard = default(IList<string>))
        {
            Move = move;
            AzurePlayerSymbol = azurePlayerSymbol;
            HumanPlayerSymbol = humanPlayerSymbol;
            Winner = winner;
            WinPositions = winPositions;
            GameBoard = gameBoard;
        }

        /// <summary>
        /// Indicates the position the Azure App Service chooses.
        /// If a tie or winner occurred because of the game state
        /// provided before Azure making a move the move property
        /// shall be set to null.
        /// </summary>
        [JsonProperty(PropertyName = "move")]
        public int? Move { get; set; }

        /// <summary>
        /// Shall be the same value the client sent
        /// </summary>
        [JsonProperty(PropertyName = "azurePlayerSymbol")]
        public string AzurePlayerSymbol { get; set; }

        /// <summary>
        /// Shall be the same value the client sent
        /// </summary>
        [JsonProperty(PropertyName = "humanPlayerSymbol")]
        public string HumanPlayerSymbol { get; set; }

        /// <summary>
        /// Indicates the gameboard status. There can be a
        /// winner, a tie, or no winner or tie yet (inconclusive)
        /// and the game can continue.
        /// </summary>
        [JsonProperty(PropertyName = "winner")]
        public string Winner { get; set; }

        /// <summary>
        /// An array that lists the zero-based position index
        /// values of the win or null if no winner is present in
        /// the gameBoard array.
        /// </summary>
        [JsonProperty(PropertyName = "winPositions")]
        public IList<int?> WinPositions { get; set; }

        /// <summary>
        /// An array containing all the positions on the board and
        /// the mark(s) indicating the positions played including
        /// the mark azure made if Azure made a move.
        /// </summary>
        [JsonProperty(PropertyName = "gameBoard")]
        public IList<string> GameBoard { get; set; }

    }
}
